syntax = "proto3";

package micromart.catalog;

service CatalogService {
  rpc CheckAvailability(CheckAvailabilityRequest) returns (CheckAvailabilityResponse);
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
}

message CheckAvailabilityRequest {
  string product_id = 1;
  int32 quantity = 2;
}

message CheckAvailabilityResponse {
  bool available = 1;
  int32 quantity_available = 2;
}

message GetProductRequest {
  string product_id = 1;
}

message GetProductResponse {
  bool found = 1;
  string id = 2;
  string sku = 3;
  string name = 4;
  string slug = 5;
  double price = 6;
  string currency = 7;
  bool is_active = 8;
  int32 quantity_available = 9;
}